BasedOnStyle: Google
Language: Cpp
AlignAfterOpenBracket: BlockIndent
AllowShortBlocksOnASingleLine: Empty
AllowShortCaseLabelsOnASingleLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: Inline
AllowShortLoopsOnASingleLine: false
BinPackArguments: true
BinPackParameters: true
BreakBeforeBraces: Attach
BreakStringLiterals: true
ColumnLimit: 80
IndentAccessModifiers: true
IndentWidth: 4
KeepEmptyLinesAtTheStartOfBlocks: false
MaxEmptyLinesToKeep: 1
PointerAlignment: Left
ReferenceAlignment: Pointer
SpacesInParentheses: false
SpaceBeforeParens: ControlStatements
SpacesInCStyleCastParentheses: false
UseTab: Never
