version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Build from the docs/ directory with Sphinx.
sphinx:
  configuration: docs/source/conf.py

# Install Python requirements.
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Generate PDF file of documentation
formats:
  - pdf
