version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

# Build from the docs/ directory with Sphinx.
sphinx:
  builder: dirhtml
  configuration: docs/source/conf.py

# Install Python requirements.
python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
