[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11~=2.6.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "prospr"
authors = [
    {author = "okkevaneck", email = "okke.van.eck@gmail.com"}
]
dynamic = ["version", "readme"]
description = "A toolbox for protein folding with Python."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = [
    "prospr",
    "protein",
    "structure",
    "prediction",
    "toolbox",
    "python",
    "c++",
    "extension",
    "pypi",
    "package",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
    "Topic :: Education",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[project.urls]
homepage = "https://github.com/okkevaneck/prospr"
documentation = "https://prospr.readthedocs.io"
repository = "https://github.com/okkevaneck/prospr"

[tool.setuptools]
platforms = ["Linux", "macOS", "Windows"]
zip-safe = false

[tool.setuptools.packages.find]
where = ["prospr"]

[tool.setuptools.package-data]
prospr = ["data/*/*.csv"]

[tool.setuptools.dynamic]
version = {attr = "prospr.__version__"}
#readme = {file = "README.md"}

[tool.black]
line-length = 79

[tool.pytest]
minversion = 7.1

[tool.pytest.ini_options]
pythonpath = [
  ".",
]
