[project]
requires-python = ">=3.6"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11~=2.6.1",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.flake8]
extend-ignore = "E203,W503"

[tool.pytest]
minversion = 6.2
