# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Protein')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Protein')
    _Protein = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Protein', [dirname(__file__)])
        except ImportError:
            import _Protein
            return _Protein
        try:
            _mod = imp.load_module('_Protein', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Protein = swig_import_helper()
    del swig_import_helper
else:
    import _Protein
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Protein.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _Protein.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Protein.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Protein.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Protein.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Protein.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Protein.SwigPyIterator_copy(self)

    def next(self):
        return _Protein.SwigPyIterator_next(self)

    def __next__(self):
        return _Protein.SwigPyIterator___next__(self)

    def previous(self):
        return _Protein.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Protein.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Protein.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Protein.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Protein.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Protein.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Protein.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Protein.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _Protein.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _Protein.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Protein.IntVector___nonzero__(self)

    def __bool__(self):
        return _Protein.IntVector___bool__(self)

    def __len__(self):
        return _Protein.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _Protein.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Protein.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Protein.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Protein.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Protein.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Protein.IntVector___setitem__(self, *args)

    def pop(self):
        return _Protein.IntVector_pop(self)

    def append(self, x):
        return _Protein.IntVector_append(self, x)

    def empty(self):
        return _Protein.IntVector_empty(self)

    def size(self):
        return _Protein.IntVector_size(self)

    def swap(self, v):
        return _Protein.IntVector_swap(self, v)

    def begin(self):
        return _Protein.IntVector_begin(self)

    def end(self):
        return _Protein.IntVector_end(self)

    def rbegin(self):
        return _Protein.IntVector_rbegin(self)

    def rend(self):
        return _Protein.IntVector_rend(self)

    def clear(self):
        return _Protein.IntVector_clear(self)

    def get_allocator(self):
        return _Protein.IntVector_get_allocator(self)

    def pop_back(self):
        return _Protein.IntVector_pop_back(self)

    def erase(self, *args):
        return _Protein.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _Protein.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _Protein.IntVector_push_back(self, x)

    def front(self):
        return _Protein.IntVector_front(self)

    def back(self):
        return _Protein.IntVector_back(self)

    def assign(self, n, x):
        return _Protein.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _Protein.IntVector_resize(self, *args)

    def insert(self, *args):
        return _Protein.IntVector_insert(self, *args)

    def reserve(self, n):
        return _Protein.IntVector_reserve(self, n)

    def capacity(self):
        return _Protein.IntVector_capacity(self)
    __swig_destroy__ = _Protein.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _Protein.IntVector_swigregister
IntVector_swigregister(IntVector)

class Protein(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Protein, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Protein, name)
    __repr__ = _swig_repr

    def __init__(self, sequence, dim=2):
        this = _Protein.new_Protein(sequence, dim)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def get_sequence(self):
        return _Protein.Protein_get_sequence(self)

    def get_dim(self):
        return _Protein.Protein_get_dim(self)

    def get_cur_len(self):
        return _Protein.Protein_get_cur_len(self)

    def get_last_pos(self):
        return _Protein.Protein_get_last_pos(self)

    def get_amino(self, position):
        return _Protein.Protein_get_amino(self, position)

    def get_score(self):
        return _Protein.Protein_get_score(self)

    def get_changes(self):
        return _Protein.Protein_get_changes(self)

    def reset(self):
        return _Protein.Protein_reset(self)

    def reset_conformation(self):
        return _Protein.Protein_reset_conformation(self)

    def is_valid(self, move):
        return _Protein.Protein_is_valid(self, move)

    def place_amino(self, move, track=True):
        return _Protein.Protein_place_amino(self, move, track)

    def remove_amino(self):
        return _Protein.Protein_remove_amino(self)

    def change_score(self, move, value):
        return _Protein.Protein_change_score(self, move, value)

    def hash_fold(self):
        return _Protein.Protein_hash_fold(self)

    def set_hash(self, fold_hash, track=False):
        return _Protein.Protein_set_hash(self, fold_hash, track)
    __swig_destroy__ = _Protein.delete_Protein
    __del__ = lambda self: None
Protein_swigregister = _Protein.Protein_swigregister
Protein_swigregister(Protein)

# This file is compatible with both classic and new-style classes.


