name: Build Package

on: [push, pull_request]

jobs:
  syntax_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: syntax_check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
          # to supply options, put them in 'env', like:
          # env:
          #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

#    test:
#        needs: build
#        runs-on: ${{ matrix.os }}
#        strategy:
#            matrix:
#                os: [ubuntu-latest, windows-latest, macos-latest]
#                python-version: [3.6]
#        steps:
#            - uses: actions/checkout@v2
#
#            -   name: Set up Python ${{ matrix.python-version }}
#                    uses: actions/setup-python@v2
#                    with:
#                        python-version: ${{ matrix.python-version }}
#
#            -   name: Install dependencies
#                    run: |
#                        python -m pip install --upgrade pip
#                        python -m pip install pytest
#                        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#
#            - name: Test with pytest
#              run: |
#                  pytest

#    deploy:
#        needs: [syntax_check, build, test]
#        runs-on: ubuntu-latest
